// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-contacts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/result.ts
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to Speedy Dialer and reconnect." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function json(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function requireUser(ctx) {
  return ctx.isAuthenticated() ? ctx.getUserId() ?? null : null;
}

// src/lib/mcp/tools/search-contacts.ts
var search_contacts_default = defineTool({
  name: "search_contacts",
  title: "Search contacts",
  description: "Search the dialer's contacts by business name, contact person or phone number. Returns matching contact records with their IDs.",
  inputSchema: {
    query: z.string().trim().min(2).describe("Business name, person name or phone number fragment."),
    limit: z.number().int().min(1).max(25).optional().describe("Maximum contacts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!requireUser(ctx)) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabase.from("contacts").select("id, business_name, contact_person, phone, email, dm_name, dm_phone, city, status, lifecycle_stage").eq("is_archived", false).or(
      `business_name.ilike.${like},contact_person.ilike.${like},phone.ilike.${like},dm_name.ilike.${like},dm_phone.ilike.${like}`
    ).limit(limit ?? 10);
    if (error) return failure(error.message);
    return json({ count: data?.length ?? 0, contacts: data ?? [] }, { contacts: data ?? [] });
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_contact_default = defineTool2({
  name: "get_contact",
  title: "Get contact detail",
  description: "Fetch one contact's full record plus its most recent call logs and notes. Use search_contacts first to find the contact ID.",
  inputSchema: {
    contact_id: z2.string().uuid().describe("The contact's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id }, ctx) => {
    if (!requireUser(ctx)) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: contact, error } = await supabase.from("contacts").select("*").eq("id", contact_id).maybeSingle();
    if (error) return failure(error.message);
    if (!contact) return failure("No contact found with that ID (or you do not have access to it).");
    const [{ data: calls }, { data: notes }] = await Promise.all([
      supabase.from("call_logs").select("id, outcome, notes, created_at, dialpad_talk_time_seconds, follow_up_date").eq("contact_id", contact_id).order("created_at", { ascending: false }).limit(10),
      supabase.from("contact_notes").select("id, content, source, created_at").eq("contact_id", contact_id).order("created_at", { ascending: false }).limit(10)
    ]);
    return json(
      { contact, recent_calls: calls ?? [], recent_notes: notes ?? [] },
      { contact_id }
    );
  }
});

// src/lib/mcp/tools/my-call-activity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var my_call_activity_default = defineTool3({
  name: "my_call_activity",
  title: "My call activity",
  description: "Summarise the signed-in rep's own call activity over the last N days: total dials, a breakdown by outcome, and total talk time.",
  inputSchema: {
    days: z3.number().int().min(1).max(90).optional().describe("Look-back window in days (default 7).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const window = days ?? 7;
    const since = new Date(Date.now() - window * 24 * 60 * 60 * 1e3).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("call_logs").select("outcome, created_at, dialpad_talk_time_seconds").eq("user_id", userId).gte("created_at", since).limit(5e3);
    if (error) return failure(error.message);
    const rows = data ?? [];
    const byOutcome = {};
    let talkSeconds = 0;
    for (const row of rows) {
      byOutcome[row.outcome] = (byOutcome[row.outcome] ?? 0) + 1;
      talkSeconds += row.dialpad_talk_time_seconds ?? 0;
    }
    return json({
      window_days: window,
      total_dials: rows.length,
      by_outcome: byOutcome,
      total_talk_minutes: Math.round(talkSeconds / 60)
    });
  }
});

// src/lib/mcp/tools/list-follow-ups.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_follow_ups_default = defineTool4({
  name: "list_follow_ups",
  title: "List my follow-ups and bookings",
  description: "List the signed-in rep's scheduled pipeline items (follow-ups and booked appointments) within a date window.",
  inputSchema: {
    days_ahead: z4.number().int().min(0).max(90).optional().describe("How far forward to look, in days (default 7)."),
    days_back: z4.number().int().min(0).max(90).optional().describe("How far back to include overdue items (default 7)."),
    pipeline_type: z4.enum(["follow_up", "booked"]).optional().describe("Restrict to one pipeline type. Omit for both.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, days_back, pipeline_type }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const ahead = days_ahead ?? 7;
    const back = days_back ?? 7;
    const from = new Date(Date.now() - back * 864e5).toISOString();
    const to = new Date(Date.now() + ahead * 864e5).toISOString();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("pipeline_items").select(
      "id, pipeline_type, status, scheduled_for, follow_up_method, notes, contact_id, contacts(business_name, contact_person, phone)"
    ).eq("assigned_user_id", userId).gte("scheduled_for", from).lte("scheduled_for", to).order("scheduled_for", { ascending: true }).limit(100);
    if (pipeline_type) query = query.eq("pipeline_type", pipeline_type);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return json({ count: data?.length ?? 0, items: data ?? [] });
  }
});

// src/lib/mcp/tools/add-contact-note.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var add_contact_note_default = defineTool5({
  name: "add_contact_note",
  title: "Add a contact note",
  description: "Add a note to a contact's timeline in the dialer, authored by the signed-in user.",
  inputSchema: {
    contact_id: z5.string().uuid().describe("The contact's UUID."),
    content: z5.string().trim().min(1).max(4e3).describe("The note text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ contact_id, content }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_notes").insert({ contact_id, content, created_by: userId, source: "manual" }).select("id, contact_id, content, created_at").maybeSingle();
    if (error) return failure(error.message);
    return json({ saved: true, note: data }, { note_id: data?.id });
  }
});

// src/lib/mcp/tools/tonights-email-round.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var tonights_email_round_default = defineTool6({
  name: "tonights_email_round",
  title: "Tonight's email round",
  description: "List the leads the signed-in rep flagged in the dialer as 'Worth an email tonight' that are still unsent. Returns each lead's name, business, recipient email, phone, when it was flagged and the latest call notes. Unsent flags carry over from previous days, so this is the full outstanding email round.",
  inputSchema: {
    include_sent_today: z6.boolean().optional().describe("Also include leads already marked sent today (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_sent_today }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contacts").select(
      "id, business_name, contact_person, email, dm_email, phone, industry, state, key_quote, follow_up_note, agreed_next_steps, last_outcome, eod_email_flagged_at, eod_email_sent_at"
    ).eq("eod_email_flagged_by", userId).not("eod_email_flagged_at", "is", null).order("eod_email_flagged_at", { ascending: false }).limit(100);
    if (error) return failure(error.message);
    const rows = data ?? [];
    const unsent = rows.filter((r) => !r.eod_email_sent_at);
    let sentToday = [];
    if (include_sent_today) {
      const startOfToday = /* @__PURE__ */ new Date();
      startOfToday.setHours(0, 0, 0, 0);
      sentToday = rows.filter(
        (r) => r.eod_email_sent_at && new Date(r.eod_email_sent_at) >= startOfToday
      );
    }
    const mapRow = (r) => ({
      contact_id: r.id,
      business_name: r.business_name,
      contact_person: r.contact_person,
      recipient_email: r.email ?? r.dm_email ?? null,
      phone: r.phone ?? null,
      industry: r.industry ?? null,
      state: r.state ?? null,
      flagged_at: r.eod_email_flagged_at,
      last_outcome: r.last_outcome ?? null,
      key_quote: r.key_quote ?? null,
      follow_up_note: r.follow_up_note ?? null,
      agreed_next_steps: r.agreed_next_steps ?? null
    });
    return json({
      unsent_count: unsent.length,
      unsent: unsent.map(mapRow),
      ...include_sent_today ? { sent_today: sentToday.map(mapRow) } : {}
    });
  }
});

// src/lib/mcp/tools/describe-data.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var DATA_DICTIONARY = {
  product: "Speedy Dialer \u2014 Odin Digital's power dialer and CRM for an Australian outbound sales team.",
  timezone_rule: "ALL daily and weekly metrics use Australia/Melbourne local-day boundaries, never UTC. A 'day' runs midnight-to-midnight in Melbourne (AEST UTC+10, AEDT UTC+11 in summer). Weeks run Monday\u2013Sunday, Melbourne time. Timestamps themselves are stored in UTC (ISO 8601); convert before grouping by day.",
  entities: {
    contacts: {
      description: "One row per lead/business. Deduplicated on (business_name, phone). GHL (GoHighLevel) is the master CRM; contacts here are the operational dialling copy.",
      key_columns: {
        id: "UUID primary key \u2014 use this to reference a contact.",
        business_name: "Business name. Placeholder names like 'Unknown' mean unenriched.",
        contact_person: "Decision-maker name, when known.",
        phone: "Main business line, E.164 format (e.g. +613\u2026). This is the number the dialer rings.",
        dm_phone: "Decision-maker direct line, E.164. Only trusted when phone_number_quality = 'confirmed'; 'suspect'/'dead' numbers must not be dialled.",
        email: "General business email.",
        dm_email: "Decision-maker email, when captured.",
        phone_number_quality: "unconfirmed | confirmed | suspect | dead \u2014 trust level of dm_phone.",
        state: "Australian state (VIC, NSW, QLD, SA, WA, TAS, NT, ACT).",
        industry: "Free-text industry.",
        is_dnc: "true = Do Not Call. Hard block \u2014 never dial, never suggest dialling.",
        last_outcome: "Outcome of the most recent logged call (see call_outcome enum).",
        key_quote: "Most useful verbatim quote captured on a call.",
        follow_up_note: "What the next call/email should say.",
        agreed_next_steps: "Next steps agreed with the prospect.",
        eod_email_flagged_at: "When a rep flagged this lead as 'worth an email tonight' in the dialer.",
        eod_email_sent_at: "When the rep marked that email as sent. Null + flagged = still owed."
      }
    },
    call_logs: {
      description: "One row per dial. The source of truth for all activity metrics.",
      key_columns: {
        user_id: "The rep who made the call (auth user id).",
        contact_id: "The lead dialled.",
        outcome: "call_outcome enum (below).",
        created_at: "UTC timestamp of the call.",
        dialpad_talk_time_seconds: "Talk time from Dialpad \u2014 the ONLY trusted source for call duration.",
        reached_connection: "Funnel stage 1: connected with a human (>15s).",
        reached_problem_awareness: "Funnel stage 2: prospect acknowledged a problem.",
        reached_solution_awareness: "Funnel stage 3: prospect engaged with the solution.",
        reached_commitment: "Funnel stage 4: prospect gave a commitment.",
        "exit_reason_*": "Why the call stalled at that stage (free-text reason codes).",
        follow_up_date: "If set, a follow-up was scheduled on this call.",
        notes: "Rep's call notes."
      }
    },
    contact_notes: {
      description: "Timeline notes on a contact. source column: manual | dialpad_summary | dialpad_transcript | ai_summary | call_transcript."
    },
    pipelines: {
      description: "Follow-up and booking pipeline rows. pipeline_type: follow_up | booked. pipeline_status: open | completed | canceled."
    }
  },
  call_outcome_enum: {
    no_answer: "Rang out / no pickup. Not a conversation.",
    voicemail: "Reached voicemail. Not a conversation.",
    gatekeeper: "Blocked by a gatekeeper; decision-maker not reached. Not a conversation.",
    not_interested: "Spoke to the prospect; declined.",
    follow_up: "Spoke to the prospect; a follow-up was scheduled.",
    booked: "Appointment booked. The primary conversion event.",
    wrong_number: "Number invalid or belongs to someone else. Excluded from connect-rate denominators where possible.",
    dnc: "Prospect asked not to be called. Number is now blocked.",
    disqualified: "Prospect is not a fit (wrong size, industry, etc.)."
  },
  kpi_definitions: {
    dials: "Count of call_logs in the window. Every logged call counts, including no_answer and wrong_number.",
    conversations: "Call logs where reached_connection = true (a real human conversation, >15s). This is the app's definition of a 'connect'.",
    connect_rate_pct: "conversations / dials \xD7 100.",
    bookings: "Call logs with outcome = 'booked'.",
    booking_rate_pct: "bookings / conversations \xD7 100 (bookings per conversation, NOT per dial).",
    talk_minutes: "Sum of dialpad_talk_time_seconds / 60, rounded.",
    funnel: "Stage counts use the reached_* boolean flags: connection \u2192 problem_awareness \u2192 solution_awareness \u2192 commitment \u2192 booked. Booked is only counted in the funnel when reached_connection is also true.",
    attribution: "Setters are credited for bookings they made; closers for appointments they sat. Appointment/revenue reporting splits these \u2014 check which one a report wants before quoting a number."
  },
  gotchas: [
    "Never use dialpad_total_duration_seconds for talk time \u2014 it includes ring time. Use dialpad_talk_time_seconds.",
    "Never count dials to is_dnc = true contacts as opportunities; they're compliance blocks.",
    "dm_phone is only trustworthy when phone_number_quality = 'confirmed'.",
    "A contact with eod_email_flagged_at set and eod_email_sent_at null is still owed an email.",
    "Contacts are deduplicated on (business_name, phone) \u2014 the same business never appears twice with the same main line."
  ]
};
var describe_data_default = defineTool7({
  name: "describe_data",
  title: "Describe the data",
  description: "Data dictionary for Speedy Dialer: what each table and column means, the call outcome vocabulary, exact KPI formulas (connect rate, booking rate, funnel stages), the Melbourne-timezone rule for daily metrics, and common traps. Call this BEFORE writing a report from other tools' output so numbers are interpreted correctly.",
  inputSchema: {
    topic: z7.enum(["all", "contacts", "call_logs", "kpis", "outcomes"]).optional().describe("Narrow the dictionary to one area (default 'all').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ topic }) => {
    const t = topic ?? "all";
    const pick = () => {
      switch (t) {
        case "contacts":
          return { contacts: DATA_DICTIONARY.entities.contacts, gotchas: DATA_DICTIONARY.gotchas };
        case "call_logs":
          return {
            call_logs: DATA_DICTIONARY.entities.call_logs,
            call_outcome_enum: DATA_DICTIONARY.call_outcome_enum,
            timezone_rule: DATA_DICTIONARY.timezone_rule
          };
        case "kpis":
          return { kpi_definitions: DATA_DICTIONARY.kpi_definitions, timezone_rule: DATA_DICTIONARY.timezone_rule };
        case "outcomes":
          return { call_outcome_enum: DATA_DICTIONARY.call_outcome_enum };
        default:
          return DATA_DICTIONARY;
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pick(), null, 2) }]
    };
  }
});

// src/lib/mcp/tools/report-snapshot.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z8 } from "npm:zod@^3.25.76";
function melbourneOffsetHours(at) {
  for (const offset of [10, 11]) {
    const shifted = new Date(at.getTime() + offset * 36e5);
    const parts = new Intl.DateTimeFormat("en-CA", {
      timeZone: "Australia/Melbourne",
      year: "numeric",
      month: "2-digit",
      day: "2-digit"
    }).format(at);
    const [y, m, d] = parts.split("-").map(Number);
    if (shifted.getUTCFullYear() === y && shifted.getUTCMonth() + 1 === m && shifted.getUTCDate() === d) {
      return offset;
    }
  }
  return 10;
}
function melbourneToday() {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Australia/Melbourne",
    year: "numeric",
    month: "2-digit",
    day: "2-digit"
  }).format(/* @__PURE__ */ new Date());
}
function melbourneDayBounds(date) {
  const noon = /* @__PURE__ */ new Date(`${date}T12:00:00Z`);
  const offset = melbourneOffsetHours(noon);
  const start = /* @__PURE__ */ new Date(`${date}T00:00:00Z`);
  start.setTime(start.getTime() - offset * 36e5);
  const end = new Date(start.getTime() + 24 * 36e5);
  return { start: start.toISOString(), end: end.toISOString() };
}
function pct(numerator, denominator) {
  return denominator ? Math.round(numerator / denominator * 1e3) / 10 : 0;
}
function summarise(logs) {
  const byOutcome = {};
  let talkSeconds = 0;
  let conversations = 0;
  let problem = 0;
  let solution = 0;
  let commitment = 0;
  let followUpsSet = 0;
  let bookings = 0;
  for (const l of logs) {
    byOutcome[l.outcome] = (byOutcome[l.outcome] ?? 0) + 1;
    talkSeconds += l.dialpad_talk_time_seconds ?? 0;
    if (l.reached_connection) conversations += 1;
    if (l.reached_problem_awareness) problem += 1;
    if (l.reached_solution_awareness) solution += 1;
    if (l.reached_commitment) commitment += 1;
    if (l.follow_up_date) followUpsSet += 1;
    if (l.outcome === "booked") bookings += 1;
  }
  return {
    dials: logs.length,
    conversations,
    connect_rate_pct: pct(conversations, logs.length),
    bookings,
    booking_rate_pct: pct(bookings, conversations),
    talk_minutes: Math.round(talkSeconds / 60),
    follow_ups_set: followUpsSet,
    funnel: {
      connection: conversations,
      problem_awareness: problem,
      solution_awareness: solution,
      commitment,
      booked: bookings
    },
    by_outcome: byOutcome
  };
}
var SELECT = "user_id, outcome, dialpad_talk_time_seconds, reached_connection, reached_problem_awareness, reached_solution_awareness, reached_commitment, follow_up_date";
var report_snapshot_default = defineTool8({
  name: "report_snapshot",
  title: "Report snapshot",
  description: "Pre-aggregated dialling metrics for a report: dials, conversations, connect rate, bookings, booking rate, talk minutes, funnel-stage counts and outcome breakdown. All day boundaries are Australia/Melbourne local time. Defaults to the signed-in rep ('me'); admins and coaches can pass scope 'team' for a per-rep breakdown. Pair with describe_data for formula definitions.",
  inputSchema: {
    date: z8.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Melbourne local date YYYY-MM-DD (default: today)."),
    days: z8.number().int().min(1).max(31).optional().describe("Number of consecutive Melbourne days ending on `date` (default 1)."),
    scope: z8.enum(["me", "team"]).optional().describe("'me' (default) or 'team' \u2014 team requires admin/coach role.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, days, scope }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const endDate = date ?? melbourneToday();
    const windowDays = days ?? 1;
    const end = melbourneDayBounds(endDate).end;
    const startDate = new Date((/* @__PURE__ */ new Date(`${endDate}T12:00:00Z`)).getTime() - (windowDays - 1) * 24 * 36e5).toISOString().slice(0, 10);
    const start = melbourneDayBounds(startDate).start;
    const supabase = supabaseForUser(ctx);
    const wantsTeam = scope === "team";
    let teamAllowed = false;
    if (wantsTeam) {
      const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", userId);
      teamAllowed = (roles ?? []).some((r) => r.role === "admin" || r.role === "coach");
      if (!teamAllowed) return failure("Team scope requires an admin or coach role.");
    }
    let query = supabase.from("call_logs").select(SELECT).gte("created_at", start).lt("created_at", end).limit(2e4);
    if (!teamAllowed) query = query.eq("user_id", userId);
    const { data, error } = await query;
    if (error) return failure(error.message);
    const logs = data ?? [];
    const result = {
      window: { start_date: startDate, end_date: endDate, days: windowDays, timezone: "Australia/Melbourne" },
      scope: teamAllowed ? "team" : "me",
      totals: summarise(logs)
    };
    if (teamAllowed) {
      const perRep = /* @__PURE__ */ new Map();
      for (const l of logs) {
        const list = perRep.get(l.user_id) ?? [];
        list.push(l);
        perRep.set(l.user_id, list);
      }
      const repIds = [...perRep.keys()];
      const { data: profiles } = await supabase.from("profiles").select("user_id, display_name, email").in("user_id", repIds);
      const names = new Map((profiles ?? []).map((p) => [p.user_id, p.display_name ?? p.email ?? "Unknown rep"]));
      result.per_rep = repIds.map((id) => ({ rep: names.get(id) ?? "Unknown rep", ...summarise(perRep.get(id)) })).sort((a, b) => b.dials - a.dials);
    }
    return json(result);
  }
});

// src/lib/mcp/index.ts
var projectRef = "xhcvwhcpaeetmmzkuwyw";
var mcp_default = defineMcp({
  name: "speedy-dialer",
  title: "Speedy Dialer",
  version: "0.1.0",
  instructions: "Tools for Speedy Dialer, Odin Digital's power dialer and CRM. Look contacts up with `search_contacts`, then use the returned ID with `get_contact` for the full record, recent calls and notes. `my_call_activity` summarises the signed-in rep's own dialling. `list_follow_ups` shows their scheduled follow-ups and booked appointments. `add_contact_note` writes a note to a contact's timeline. `tonights_email_round` lists the leads they flagged in the dialer as worth an email tonight that are still unsent. For REPORTS: call `describe_data` first for column meanings, outcome vocabulary, KPI formulas and the Melbourne-timezone rule, then `report_snapshot` for pre-aggregated dials/conversations/bookings/talk-time (per rep, or team-wide for admins). All access runs as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_contacts_default, get_contact_default, my_call_activity_default, list_follow_ups_default, add_contact_note_default, tonights_email_round_default, describe_data_default, report_snapshot_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
