// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-contacts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/result.ts
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to Speedy Dialer and reconnect." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function json(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function requireUser(ctx) {
  return ctx.isAuthenticated() ? ctx.getUserId() ?? null : null;
}

// src/lib/mcp/tools/search-contacts.ts
var search_contacts_default = defineTool({
  name: "search_contacts",
  title: "Search contacts",
  description: "Search the dialer's contacts by business name, contact person or phone number. Returns matching contact records with their IDs.",
  inputSchema: {
    query: z.string().trim().min(2).describe("Business name, person name or phone number fragment."),
    limit: z.number().int().min(1).max(25).optional().describe("Maximum contacts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!requireUser(ctx)) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabase.from("contacts").select("id, business_name, contact_person, phone, email, dm_name, dm_phone, city, status, lifecycle_stage").eq("is_archived", false).or(
      `business_name.ilike.${like},contact_person.ilike.${like},phone.ilike.${like},dm_name.ilike.${like},dm_phone.ilike.${like}`
    ).limit(limit ?? 10);
    if (error) return failure(error.message);
    return json({ count: data?.length ?? 0, contacts: data ?? [] }, { contacts: data ?? [] });
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_contact_default = defineTool2({
  name: "get_contact",
  title: "Get contact detail",
  description: "Fetch one contact's full record plus its most recent call logs and notes. Use search_contacts first to find the contact ID.",
  inputSchema: {
    contact_id: z2.string().uuid().describe("The contact's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id }, ctx) => {
    if (!requireUser(ctx)) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: contact, error } = await supabase.from("contacts").select("*").eq("id", contact_id).maybeSingle();
    if (error) return failure(error.message);
    if (!contact) return failure("No contact found with that ID (or you do not have access to it).");
    const [{ data: calls }, { data: notes }] = await Promise.all([
      supabase.from("call_logs").select("id, outcome, notes, created_at, dialpad_talk_time_seconds, follow_up_date").eq("contact_id", contact_id).order("created_at", { ascending: false }).limit(10),
      supabase.from("contact_notes").select("id, content, source, created_at").eq("contact_id", contact_id).order("created_at", { ascending: false }).limit(10)
    ]);
    return json(
      { contact, recent_calls: calls ?? [], recent_notes: notes ?? [] },
      { contact_id }
    );
  }
});

// src/lib/mcp/tools/my-call-activity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var my_call_activity_default = defineTool3({
  name: "my_call_activity",
  title: "My call activity",
  description: "Summarise the signed-in rep's own call activity over the last N days: total dials, a breakdown by outcome, and total talk time.",
  inputSchema: {
    days: z3.number().int().min(1).max(90).optional().describe("Look-back window in days (default 7).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const window = days ?? 7;
    const since = new Date(Date.now() - window * 24 * 60 * 60 * 1e3).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("call_logs").select("outcome, created_at, dialpad_talk_time_seconds").eq("user_id", userId).gte("created_at", since).limit(5e3);
    if (error) return failure(error.message);
    const rows = data ?? [];
    const byOutcome = {};
    let talkSeconds = 0;
    for (const row of rows) {
      byOutcome[row.outcome] = (byOutcome[row.outcome] ?? 0) + 1;
      talkSeconds += row.dialpad_talk_time_seconds ?? 0;
    }
    return json({
      window_days: window,
      total_dials: rows.length,
      by_outcome: byOutcome,
      total_talk_minutes: Math.round(talkSeconds / 60)
    });
  }
});

// src/lib/mcp/tools/list-follow-ups.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_follow_ups_default = defineTool4({
  name: "list_follow_ups",
  title: "List my follow-ups and bookings",
  description: "List the signed-in rep's scheduled pipeline items (follow-ups and booked appointments) within a date window.",
  inputSchema: {
    days_ahead: z4.number().int().min(0).max(90).optional().describe("How far forward to look, in days (default 7)."),
    days_back: z4.number().int().min(0).max(90).optional().describe("How far back to include overdue items (default 7)."),
    pipeline_type: z4.enum(["follow_up", "booked"]).optional().describe("Restrict to one pipeline type. Omit for both.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, days_back, pipeline_type }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const ahead = days_ahead ?? 7;
    const back = days_back ?? 7;
    const from = new Date(Date.now() - back * 864e5).toISOString();
    const to = new Date(Date.now() + ahead * 864e5).toISOString();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("pipeline_items").select(
      "id, pipeline_type, status, scheduled_for, follow_up_method, notes, contact_id, contacts(business_name, contact_person, phone)"
    ).eq("assigned_user_id", userId).gte("scheduled_for", from).lte("scheduled_for", to).order("scheduled_for", { ascending: true }).limit(100);
    if (pipeline_type) query = query.eq("pipeline_type", pipeline_type);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return json({ count: data?.length ?? 0, items: data ?? [] });
  }
});

// src/lib/mcp/tools/add-contact-note.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var add_contact_note_default = defineTool5({
  name: "add_contact_note",
  title: "Add a contact note",
  description: "Add a note to a contact's timeline in the dialer, authored by the signed-in user.",
  inputSchema: {
    contact_id: z5.string().uuid().describe("The contact's UUID."),
    content: z5.string().trim().min(1).max(4e3).describe("The note text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ contact_id, content }, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_notes").insert({ contact_id, content, created_by: userId, source: "manual" }).select("id, contact_id, content, created_at").maybeSingle();
    if (error) return failure(error.message);
    return json({ saved: true, note: data }, { note_id: data?.id });
  }
});

// src/lib/mcp/index.ts
var projectRef = "xhcvwhcpaeetmmzkuwyw";
var mcp_default = defineMcp({
  name: "speedy-dialer",
  title: "Speedy Dialer",
  version: "0.1.0",
  instructions: "Tools for Speedy Dialer, Odin Digital's power dialer and CRM. Look contacts up with `search_contacts`, then use the returned ID with `get_contact` for the full record, recent calls and notes. `my_call_activity` summarises the signed-in rep's own dialling. `list_follow_ups` shows their scheduled follow-ups and booked appointments. `add_contact_note` writes a note to a contact's timeline. All access runs as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_contacts_default, get_contact_default, my_call_activity_default, list_follow_ups_default, add_contact_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
